### ISSUE TITLE
The build doesn't have ALAC support.

### ISSUE THREAD

**Issue by meoow** [DeaDBeeF-for-Windows/deadbeef#10]
The windows build cannot play M4A audio files of ALAC codec.

**Comment by kuba160** [comment]
You could probably see that alac is supported on https://deadbeef-for-windows.github.io/ . However I just noticed it is missing from premake script and is not a part of build anymore. ALAC plugin was available and working in versions with and before 2018-04-30.

As a workaround for now I suggest:

1. Download old version with alac plugin from https://github.com/DeaDBeeF-for-Windows/deadbeef/releases/download/2018-04-30/deadbeef-x86_64-GTK2.zip and extract it.
2. Copy file `plugins/alac.dll` and copy it to your plugins directory.
3. You will now probably lack libaries to run alac plugin. Copy the libraries found in main directory (these starting with `lib`) and move them to your deadbeef directory. Do not replace any file, just copy the missing ones.

**Comment by kuba160** [comment]
Fixed in ee678f2a20da1f72f5fa9091fe87f46e2288f965. Please check the newest version.
