### ISSUE TITLE
shellexec plugin missing

### ISSUE THREAD

**Issue by cpuuntery** [DeaDBeeF-for-Windows/deadbeef#15]
### Steps to reproduce the problem
Try to add open containing folder to the context menu in deadbeef running under windows
### What's going on? Describe the problem in as much detail as possible.
the option exists to open containing folder to the context menu if you are running Linux. but if you are running windows the option is not available. and I know the fact that Windows uses backward slash and Linux uses forward slash. and for whatever reason, the plugin ShellExec can not be compiled for windows. I can understand why ffmpeg plugin can not be compiled for windows because ffmpeg is complex so that to be expected. but the ShellExec plugin is very simple. so I hope that you can make ShellExec run under windows. or you can give me patched dll that I can put in the plugin folder 
### Information about the software:
Deadbeef version:1.8.2
OS: windows
[![Capture.png](https://i.postimg.cc/NG3HY9n2/Capture.png)](https://postimg.cc/c6cHBH0d)
[![Capture.png](https://i.postimg.cc/05DNYttr/Capture.png)](https://postimg.cc/t7RyyzGH)
[![On-Paste-20191222-170142.png](https://i.postimg.cc/HW2dpjBs/On-Paste-20191222-170142.png)](https://postimg.cc/w37S2qCS)

**Comment by cpuuntery** [comment]
@kuba160 I was able to fix it by downloading the dll from this [link](https://github.com/DeaDBeeF-for-Windows/deadbeef/releases/download/2018-04-30/deadbeef-x86_64-GTK2.zip) .and copy it to the plugin folder .and delete the config folder to force deadbeef to use gtk2 instead of gtk3 .ShellExec does not work if you use gtk3 and you need to create a .bat file to convert the forward-slash to backward-slash 
the bat file should be inside the deadbeef directory 
bat file code 
`@echo off
set folder_path=%~1
set the_path=%folder_path:/=\%
explorer.exe %the_path:'="%`
the ShellExec command is `open_folder.bat "%D"`

**Comment by kuba160** [comment]
You can download GTK2+GTK3 version and extract shellexec for both GTK versions I suppose, the link you sent excludes all GTK3 plugins, correct link is https://github.com/DeaDBeeF-for-Windows/deadbeef/releases/download/2018-04-30/deadbeef-x86_64.zip

The slash conversion is another point that needs to be looked at. Current to do list would be then:

- [X] Create premake5 build script for shellexec
- [x] Implement conversion from internal forward slash to original backward slash for compatibility
- [x] Add information to [Windows plugin status wiki page](https://github.com/DeaDBeeF-Player/deadbeef/wiki/Windows-plugin-status)

**Comment by kuba160** [comment]
Newest release 2020-05-02 includes shellexec and does not require script to work with the directories.
If you find any issues with it, please let me know.
