### ISSUE TITLE
TTA Plugin Seems to Work Fine?

### ISSUE THREAD

**Issue by Keith-Cancel** [DeaDBeeF-for-Windows/deadbeef#17]
Is there any reason that it was excluded from the windows release? It seems pretty self contained. I just compiled it and is running without any issue that I can observe from just using it. Was there some problem with it?

I also observe that it is not listed here:
https://github.com/DeaDBeeF-Player/deadbeef/wiki/Windows-plugin-status

So I, built the TTA plugin with with the following:
```
gcc -O3 ttaplug.c ttadec.c -fPIC -shared -o tta.dll
```

**Comment by kuba160** [comment]
Thank you for the information. tta plugin was not tested. I even forgot it and did not include it on the list. But if you say it is working fine, I might add it to premake file

**Comment by Keith-Cancel** [comment]
Yea seems to work fine on my system. Like it's even reading embedded CUE sheet info just fine in the tta files.

![tta](https://user-images.githubusercontent.com/8355441/78662228-9315fd80-78bf-11ea-85f8-054aa0fc758e.png)

![tta2](https://user-images.githubusercontent.com/8355441/78662231-94dfc100-78bf-11ea-9a65-9f617b3a9009.png)

**Comment by kuba160** [comment]
tta plugin added to premake in 627d5cbe9bf012c5cc4c511483bcf43806943d8b
