### ISSUE TITLE
Resample rate increase to increase in speed/tempo of playback

### ISSUE THREAD

**Issue by vishwesh-sharma** [DeaDBeeF-for-Windows/deadbeef#24]
### Information about the software:

Deadbeef version:2020-05-02
OS:Windows 10 Enterprise

**Comment by kuba160** [comment]
I guess this is intended as increasing the sample rate only changes output samplerate. For example if you play 44.1 kHz file on 88.2 kHz settings it is going to play faster at higher pitch. There is DSP Resampler in DSP and if you set "Autodetect samplerate from output device" it should automatically resample music to the output samplerate you set up.

**Comment by vishwesh-sharma** [comment]
Thanks that works, also wanted to know f I can create a feature request for enabling ASIO output on Windows.

**Comment by kuba160** [comment]
I researched that topic and found out that portaudio library version from msys2 do not provide asio output, even though portaudio is capable of it. I never used/needed ASIO. I found that somebody compiled portaudio with ASIO support:
https://github.com/spatialaudio/portaudio-binaries
You can try to download `libportaudio64bit.dll` and replace `libportaudio-2.dll` located in deadbeef directory.
