### ISSUE TITLE
DeadBeef for Windows crashes when it tries to open .m4a file

### ISSUE THREAD

**Issue by hmslima** [DeaDBeeF-for-Windows/deadbeef#26]
When I try to open a .m4a file, DeadBeef is abruptly closed. I didn't have this issue in the Linux version.

**DeadBeef version:** 2020-07-06
**Windows version:** 10 _Build 20H2_

I need to say that the version 2020-05-02 of DeadBeef for Windows can run this file with no issue. This is surely a new bug brought by the version 2020-07-06.

**Comment by kuba160** [comment]
Deadbeef version 2020-07-06 was the last version published by me. From that day you can download official builds straight from deadbeef official sourceforge page. I updated Releases page to include this information. Nevertheless it looks like the file plays without any problems in current nightly version. You can download newest nightly from [here](https://sourceforge.net/projects/deadbeef/files/travis/windows/master/).
