### ISSUE TITLE
Add file association

### ISSUE THREAD

**Issue by mrkaban** [DeaDBeeF-for-Windows/deadbeef#8]
### Information about the software:

Deadbeef version:
OS: Windows 10 x64

Здравствуйте, Планируется ли ассоциация файлов? очень не хватает пункта "Ассоциировать" и открыть музыку по умолчанию в нем.

**Comment by kuba160** [comment]
Hello, I am not russian speaker, from what I understood using google translate you talk about broken file association (like opening .mp3 files from file browser will automatically open it in deadbeef), right? It is indeed not implemented (althrough adding deadbeef as an app with an executable path manually should technically work)

**Comment by mrkaban** [comment]
I'm sorry. I read that the author of the program is Russian-speaking, and wrote in Russian. Just a music player without a file association is not convenient to use.

**Comment by kuba160** [comment]
I always add music through dialogs inside DeaDBeeF and drag-n-drop which also works, so I never bothered about adding file association. I can look it up how to add it. However it should be possible to add association manually by providing path to deadbeef executable.

**Comment by mrkaban** [comment]
I have a large Russian-language site about free software (attendance of about 1,500 people per day). I am sorry, but I will say straight. This player looks interesting and beautiful, I’d still have to fasten the themes in the Aimp style, but 99.9% of my visitors will not use it without file associations.

**Comment by kuba160** [comment]
This project does not have any people that are interested into adding features right now. I am kind of already happy with its state (except missing converter), so I don't spend much time on it.

I can try to add file association to the installer, it should not be hard.

**Comment by kuba160** [comment]
I added file association to the newest installed and adjusted the build.
https://github.com/DeaDBeeF-for-Windows/deadbeef/releases/tag/2019-06-08

There are still probably some cases where adding file(s) through association won't work.

**Comment by mrkaban** [comment]
Thanks for the file association! Added a program to my site, here is the [link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D0%BC%D1%83%D0%BB%D1%8C%D1%82%D0%B8%D0%BC%D0%B5%D0%B4%D0%B8%D0%B0/%D0%B2%D0%BE%D1%81%D0%BF%D1%80%D0%BE%D0%B8%D0%B7%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5/deadbeef-for-windows.html), it is in Russian.

From the wishes, I would like some themes, except for changing the color of individual parts and windows.

**Comment by kuba160** [comment]
Theming is handled by GTK, on linux systems it simply adapts to your desktop theme automatically. On windows it uses special theme to make it look more native. It is possible to change theme, but currently it needs to be done manually.

To change theme:
1. Download some GTK3 theme for example [Bubble-Dark-Blue](https://www.gnome-look.org/p/1253999/).
2. Put theme (unzipped) in `DeaDBeeF/share/themes`
3. Change theme in `DeaDBeeF/etc/gtk-3.0/settings.ini` (replace `gtk-theme-name = Windows-10` with `gtk-theme-name = Bubble-Dark-Blue`

Result:

![image](https://user-images.githubusercontent.com/6359901/59158592-7735a580-8abc-11e9-9807-305f83665fdb.png)

If you feel that theme choosing is important and it should be easier, please open another issue so things can be discussed.

**Comment by ghost** [comment]
for those wondering why this method did not work, the directory "\usr\themes" seems to have changed to "\share\themes"

thanks for the amazing software @kuba160 !

**Comment by kuba160** [comment]
Cannot believe I didn't see this before, thanks for sharing.
